---
title: "PM 566: Final Project"
author: Catherine Le
---

PM 566: FALL 2023

Website created by Catherine Le

# Downloadable Written Report

[here](Written-Report.pdf) to download the written report.

[Click here to download](../Written-Report.pdf) This link has the slashes.

# Brief Description

The question I am exploring in this final project is "What is the correlation between physical activity levels (e.g., reported exercise frequency) and diet habits (e.g., daily consumption of vegetables)?" The intention of this final project is to further explore the stereotype that people who eat healthier also exercise often.

To answer this question, I used the data set "Nutrition, Physical Activity, and Obesity - Behavioral Risk Factor Surveillance System" (BRFSS). BRFSS is an on-going, state-based telephone survey conducted by the CDC and state health departments. The data includes self-reported information on nutrition, behavioral risk factors, and physical activity levels for all 50 U.S. states.

To get the data ready for exploration, I checked for missing values and implausible values (i.e., percentages under 0 and over 100). I then wrangled the data by filtering the data for rows that contained the survey questions "percent of adults who engage in no leisure-time physical activity" and "percent of adults who report consuming vegetables less than one time daily." To explore the data for any patterns, I created histograms and scatterplots.

By creating a scatter plot between the variables "percentage of adults engaging in no leisure time activity" and "percentage of adults consuming vegetables less than one time daily", I found that there was a positive correlation between the two. You can explore my findings further in the interactive graphics down below.

# Interactive Figures

```{r}
1 + 1
```
